export enum FieldTypeEnum {
  bigint = 'bigint',
  bigserial = 'bigserial',
  bit = 'bit',
  'bit varying' = 'bit varying',
  boolean = 'boolean',
  box = 'box',
  bytea = 'bytea',
  character = 'character',
  'character varying' = 'character varying',
  cidr = 'cidr',
  circle = 'circle',
  date = 'date',
  'double precision' = 'double precision',
  inet = 'inet',
  integer = 'integer',
  interval = 'interval',
  json = 'json',
  jsonb = 'jsonb',
  line = 'line',
  lseg = 'lseg',
  macaddr = 'macaddr',
  money = 'money',
  numeric = 'numeric',
  path = 'path',
  pg_lsn = 'pg_lsn',
  point = 'point',
  polygon = 'polygon',
  real = 'real',
  smallint = 'smallint',
  smallserial = 'smallserial',
  serial = 'serial',
  text = 'text',
  time = 'time',
  timestamp = 'timestamp',
  tsquery = 'tsquery',
  tsvector = 'tsvector',
  txid_snapshot = 'txid_snapshot',
  uuid = 'uuid',
  xml = 'xml',
  int8 = 'int8',
  serial8 = 'serial8',
  varbit = 'varbit',
  bool = 'bool',
  char = 'char',
  varchar = 'varchar',
  float8 = 'float8',
  int = 'int',
  int4 = 'int4',
  decimal = 'decimal',
  float4 = 'float4',
  int2 = 'int2',
  serial2 = 'serial2',
  serial4 = 'serial4',
  timetz = 'timetz',
  timestamptz = 'timestamptz',
}

export enum OperatorEnum {
  _eq = '=',
  _neq = '<>',
  _in = 'IN',
  _nin = 'NOT IN',
  _gt = '>',
  _gte = '>=',
  _lt = '<',
  _lte = '<=',
  _isnull = 'IS NULL',
  _like = 'LIKE',
  _ilike = 'ILIKE',
  _nlike = 'NOT LIKE',
}

export enum AggregateEnum {
  'count',
  'min',
  'max',
  'avg',
  'sum',
}

export enum ReservedDefaultValueEnum {
  'clock_timestamp()',
  current_date,
  current_time,
  current_timestamp,
  localtime,
  localtimestamp,
  'now()',
  'statement_timestamp()',
  'timeofday()',
  'transaction_timestamp()',
}

export enum QueryTypeEnum {
  select = 'select',
  insert = 'insert',
  update = 'update',
  delete = 'delete',
  aggregate = 'aggregate',
}
